# Generated by Django 4.2.23 on 2025-06-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(help_text="Telegram chat ID", unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="Telegram username", max_length=100
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="User's first name", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="User's last name", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send notifications to this subscriber",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Subscriber",
                "verbose_name_plural": "Telegram Subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
