# Generated by Django 4.2.23 on 2025-06-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_telegramsubscriber_delete_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramsubscriber",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="telegramsubscriber",
            name="last_name",
        ),
        migrations.AddField(
            model_name="telegramsubscriber",
            name="name",
            field=models.CharField(blank=True, help_text="User's name", max_length=100),
        ),
    ]
